Repository MOBI-BattleTalk/BattleTalk, pull requests merged in 2024-01, with the labels that each got.

#38 Feat : create battle page 이미지 업로드
  public/smallLogo.png
  src/apis/auth.ts
  src/apis/index.ts
  src/assets/Photo.svg
  src/hooks/useGetInputFile.tsx
  src/mock/commentMock.ts
  src/pages/CreateBattlePage/components/BattleOption.tsx
  src/pages/CreateBattlePage/components/BattleTopic.tsx
  src/pages/CreateBattlePage/components/Category.tsx
  src/pages/CreateBattlePage/components/CreateForm.tsx
  src/pages/CreateBattlePage/index.tsx
  src/pages/DetailPage/components/ColorCommentList.tsx
  src/pages/DetailPage/components/CommentBox.tsx
  src/pages/LoginPage/components/SignIn.tsx
  src/pages/LoginPage/components/SignUp.tsx
  src/types/postType.ts
  src/types/userType.ts
Labels: development, refactor

#39 Feat : endPoint 등 상수화, commentMock 수정
  public/MainLogo.png
  src/apis/auth.ts
  src/apis/core.ts
  src/assets/GoBack.svg
  src/atoms/index.ts
  src/components/BasicModal.tsx
  src/components/Button.tsx
  src/components/GoBackButton.tsx
  src/components/ImageBox.tsx
  src/components/Input.tsx
  src/components/TopButton.tsx
  src/const/EndPoint.ts
  src/const/Keys.ts
  src/layout/components/BattleCreateButton.tsx
  src/layout/components/Header.tsx
  src/layout/components/LoginButton.tsx
  src/layout/components/ProfileButton.tsx
  src/mock/commentMock.ts
  src/pages/CreateBattlePage/components/BattleOption.tsx
  src/pages/CreateBattlePage/index.tsx
  src/pages/DetailPage/components/ColorCommentList.tsx
  src/pages/DetailPage/components/CommentBox.tsx
  src/pages/LoginPage/components/FormChangeBtn.tsx
  src/pages/LoginPage/components/SignIn.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/components/MainBattleCard.tsx
  src/router/routing.tsx
  src/types/postType.ts
  src/types/userType.ts
Labels: style, development, refactor

#42 Feat : CreateBattlePage post 요청 구현
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/post.ts
  src/const/EndPoint.ts
  src/const/ModalMessage.ts
  src/pages/CreateBattlePage/components/BattleOption.tsx
  src/pages/CreateBattlePage/components/CreateForm.tsx
  src/pages/CreateBattlePage/index.tsx
  src/types/postType.ts
Labels: development, api, refactor

#41 Feat : Refresh token 구현
  src/apis/auth.ts
  src/apis/core.ts
  src/mock/postMock.ts
  src/pages/CreateBattlePage/index.tsx
  src/pages/DetailPage/components/CommentList.tsx
  src/pages/DetailPage/components/DetailBattleCard.tsx
  src/pages/DetailPage/index.tsx
  src/pages/LoginPage/components/FormChangeBtn.tsx
  src/pages/LoginPage/components/SignIn.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/components/MainBattleCard.tsx
  src/pages/MainPage/index.tsx
Labels: style, development

#43 Feat : toast message 구현
  src/pages/LoginPage/components/SignIn.tsx
  src/pages/LoginPage/components/SignUp.tsx
  src/pages/LoginPage/index.tsx
  src/utils/toastMessage.tsx
Labels: style, development

#40 Feat : nickName수정 구현, CSS수정
  src/apis/auth.ts
  src/components/ProfileModal.tsx
  src/types/userType.ts
Labels: style, development, api

#44 Feat : mock data setting
  src/apis/auth.ts
  src/apis/post.ts
  src/components/BattleEnterModal.tsx
  src/components/ImageBox.tsx
  src/components/ProfileModal.tsx
  src/components/ResultBar.tsx
  src/const/EndPoint.ts
  src/layout/components/Header.tsx
  src/mock/commentMock.ts
  src/mock/postMock.ts
  src/pages/DetailPage/components/BattleJoinModal.tsx
  src/pages/DetailPage/components/ColorCommentList.tsx
  src/pages/DetailPage/components/CommentBox.tsx
  src/pages/DetailPage/components/CommentList.tsx
  src/pages/DetailPage/components/DetailBattleCard.tsx
  src/pages/DetailPage/index.tsx
  src/pages/MainPage/components/BattleHeader.tsx
  src/pages/MainPage/components/MainBattleCard.tsx
  src/pages/MainPage/index.tsx
  src/types/postType.ts
  src/types/userType.ts
  src/utils/toastMessage.tsx
Labels: style, development

#45 Feat : 배틀 생성 버튼 close
  src/const/ModalMessage.ts
  src/layout/HeaderLayout.tsx
  src/layout/components/BattleCreateButton.tsx
  src/layout/components/ProfileButton.tsx
  src/pages/DetailPage/components/ColorCommentList.tsx
Labels: refactor

#46 Feat : MainPage data get요청
  src/apis/auth.ts
  src/apis/post.ts
  src/components/BasicModal.tsx
  src/components/ProfileModal.tsx
  src/components/ResultBar.tsx
  src/components/ResultCss.ts
  src/const/EndPoint.ts
  src/const/queryKey.ts
  src/pages/CreateBattlePage/components/CreateForm.tsx
  src/pages/DetailPage/components/BattleJoinModal.tsx
  src/pages/MainPage/components/BattleHeader.tsx
  src/pages/MainPage/components/MainBattleCard.tsx
  src/pages/MainPage/index.tsx
  src/types/postType.ts
Labels: development, api

#48 Feat : 디테일 페이지 이동
  src/apis/post.ts
  src/const/queryKey.ts
  src/mock/commentMock.ts
  src/pages/DetailPage/components/DetailBattleCard.tsx
  src/pages/DetailPage/index.tsx
  src/pages/MainPage/index.tsx
  src/types/postType.ts
Labels: development, api, refactor

#50 Feat : Nickname 수정시 즉시 반영
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/atom/user.ts
  src/components/ProfileModal.tsx
  src/layout/HeaderLayout.tsx
  src/layout/components/Header.tsx
  src/pages/LoginPage/components/SignIn.tsx
  src/utils/toastMessage.tsx
Labels: style, development

#54 Fix : mainPage + detailPage 타입 에러 해결
  src/apis/post.ts
  src/mock/commentMock.ts
  src/mock/postMock.ts
  src/pages/DetailPage/components/BattleJoinModal.tsx
  src/pages/DetailPage/components/DetailBattleCard.tsx
  src/pages/MainPage/index.tsx
  src/types/postType.ts
Labels: bug
