Repository MOBI-BattleTalk/BattleTalk, pull requests merged in 2024-02, with the labels that each got.

#58 Bt 62 toast message refactor
  README.md
  src/components/ProfileModal.tsx
  src/pages/DetailPage/components/BattleJoinModal.tsx
  src/pages/LoginPage/components/SignIn.tsx
  src/pages/LoginPage/components/SignUp.tsx
  src/utils/toastMessage.tsx
Labels: development, refactor

#59 Bt 63 refactor navigate
  src/apis/auth.ts
  src/apis/post.ts
  src/atom/user.ts
  src/components/FormCard.tsx
  src/components/Input.tsx
  src/components/ProfileModal.tsx
  src/components/ResultBar.tsx
  src/components/Textarea.tsx
  src/const/queryKey.ts
  src/layout/components/ProfileButton.tsx
  src/main.tsx
  src/pages/CreateBattlePage/components/BattleOption.tsx
  src/pages/CreateBattlePage/components/BattleTopic.tsx
  src/pages/CreateBattlePage/components/Category.tsx
  src/pages/CreateBattlePage/index.tsx
  src/pages/DetailPage/components/BattleJoinButton.tsx
  src/pages/DetailPage/components/BattleJoinModal.tsx
  src/pages/DetailPage/components/CommentList.tsx
  src/pages/DetailPage/components/DetailBattleCard.tsx
  src/pages/DetailPage/index.tsx
  src/pages/LoginPage/components/FormChangeBtn.tsx
  src/pages/LoginPage/components/SignIn.tsx
  src/pages/MainPage/components/MainBattleCard.tsx
  src/pages/MainPage/index.tsx
  src/pages/ModalPage/index.tsx
  src/router/routing.tsx
  src/types/postType.ts
  src/utils/toastMessage.tsx
Labels: bug, refactor

#60 Docs : 리드미 수정
  README.md
Labels: docs

#62 Fix : 반응형 css 수정
  src/pages/CreateBattlePage/components/CreateForm.tsx
  src/pages/DetailPage/components/BattleJoinModal.tsx
  src/pages/DetailPage/components/ColorCommentList.tsx
  src/pages/DetailPage/components/CommentList.tsx
  src/pages/DetailPage/components/DetailBattleCard.tsx
  src/pages/DetailPage/index.tsx
  src/pages/MainPage/index.tsx
Labels: refactor

#67 Feat : 스켈레톤 UI 구현
  package-lock.json
  src/hooks/useObserver.tsx
  src/pages/MainPage/components/skeletonUi.tsx
  src/pages/MainPage/index.tsx
Labels: style

#68 Feat : 댓글 인피니티 스크롤 구현
  src/apis/post.ts
  src/pages/DetailPage/components/CommentBox.tsx
  src/pages/DetailPage/components/CommentList.tsx
  src/pages/DetailPage/index.tsx
  src/types/postType.ts
Labels: development

#69 Refactor : topButton 컨벤션
  src/components/TopButton.tsx
Labels: refactor
